### ISSUE TITLE
Failed to add AppLovin Quality Service Plugin

### ISSUE THREAD

**Issue by tomasd-ecorush** [AppLovin/AppLovin-MAX-Unity-Plugin#220]
### MAX Plugin Version

5.6.4

### Unity Version

2022.2.2

### Device/Platform Info

Unity Editor, Android Target

### Current Behavior

This error shows in console after the build process

`Error [AppLovin MAX] Failed to add AppLovin Quality Service plugin. Quality Service Plugin Added?: False, Quality Service Repo added?: False, Quality Service dependency added?: False
UnityEngine.Debug:LogError (object)
MaxSdkLogger:UserError (string) (at Assets/MaxSdk/Scripts/MaxSdkLogger.cs:55)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:GenerateUpdatedBuildFileLines (System.Collections.Generic.List`1<string>,string,bool) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:415)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:AddQualityServiceBuildScriptLines (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:115)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinPostProcessGradleProject:OnPostGenerateGradleAndroidProject (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessAndroidGradle.cs:30)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`

### Expected Behavior

The build process will complete without errors.

### How to Reproduce

1. Import Applovin MAX 5.6.4
2. Enable checkbox "Enable MAX Ad Review" and paste Applovin SDK Key
3. Build APK

**Comment by alvarshahanji** [comment]
Hi, it seems like the issue started specifically with Unity 2022.2.0. Unity has significantly changed the how Gradle files are generated. We'll have a fix for it in the next release.

If you have unchecked the Enable Ad Review setting in our Integration Manager and still see the error, you can safely ignore it for now.

If you would like to get rid of the error, you can try adding the following line (shown with a + at the start) to the AppLovinPostProcessGradleProject file.

        public void OnPostGenerateGradleAndroidProject(string path)
        {
#if UNITY_2019_3_OR_NEWER
+            if (!AppLovinSettings.Instance.QualityServiceEnabled) return;


You can follow discussion on the same issue [here](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/206) as well

**Comment by joshua-matchala** [comment]
When is this going to be fixed? I was already told early January.. @alvarshahanji

**Comment by santoshbagadi** [comment]
This has been fixed in our latest Unity plugin [version 5.6.5](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_6_5).

**Comment by joshua-matchala** [comment]
@santoshbagadi 
This is not fixed. It builds once, and if you do subsequent builds it fails with this error:

`CommandInvokationFailure: Gradle build failed. 
/Users/josh/Documents/UnityEditors/2022.2.2f1/PlaybackEngines/AndroidPlayer/OpenJDK/bin/java -classpath "/Users/josh/Documents/UnityEditors/2022.2.2f1/PlaybackEngines/AndroidPlayer/Tools/gradle/lib/gradle-launcher-7.2.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleDebug"

Environment Variables:
BURST_ANDROID_MIN_API_LEVEL = 22
XPC_FLAGS = 0x0
JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF-8
MallocNanoZone = 0
ORIGINAL_XDG_CURRENT_DESKTOP = undefined
SHELL = /bin/zsh
SSH_AUTH_SOCK = /private/tmp/com.apple.launchd.qR15c70ZSu/Listeners
HOME = /Users/josh
PATH = /usr/bin:/bin:/usr/sbin:/sbin
__CFBundleIdentifier = com.unity3d.unityhub
USER = josh
__CF_USER_TEXT_ENCODING = 0x1F5:0x0:0x0
TMPDIR = /var/folders/yv/bss8v16d5n5grdvgj86_dk1c0000gn/T/
LOGNAME = josh
JAVA_HOME = /Users/josh/Documents/UnityEditors/2022.2.2f1/PlaybackEngines/AndroidPlayer/OpenJDK
ANDROID_NDK_ROOT = /Users/josh/Documents/UnityEditors/2022.2.2f1/PlaybackEngines/AndroidPlayer/NDK
XPC_SERVICE_NAME = application.com.unity3d.unityhub.95309340.95309346
COMMAND_MODE = unix2003


stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/josh/Documents/GitHub/RyahsRhythm/Library/Bee/Android/Prj/IL2CPP/Gradle/build.gradle' line: 10

* What went wrong:
Plugin with id 'com.applovin.quality' was already requested at line 9

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
]
stdout[

]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action`1[T] progress) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, Unity.Android.Gradle.AndroidGradle androidGradle, System.String workingdir, System.String task, System.Action`1[T] progress) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <78a7f7e9a87745b9a9f63bc62bfdda7d>:0)
UnityEditor.BuildPipeline:BuildPlayer(EditorBuildSettingsScene[], String, BuildTarget, BuildOptions)
BuildWindow:BuildAndRunAndroidToDevice(Boolean) (at Assets/Branch/Editor/BuildWindow.cs:147)
BuildWindow:OnGUI() (at Assets/Branch/Editor/BuildWindow.cs:24)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)
`

**Comment by santoshbagadi** [comment]
@joshua-matchala is this when building an `.apk`/ `Build and Run` or are you trying to export an Android project?

**Comment by joshua-matchala** [comment]
@santoshbagadi its a build and run to device.

**Comment by santoshbagadi** [comment]
Would you mind sharing the `build.gradle` file generated here: `/Users/josh/Documents/GitHub/RyahsRhythm/Library/Bee/Android/Prj/IL2CPP/Gradle/build.gradle`

**Comment by joshua-matchala** [comment]
@santoshbagadi 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/75960319/214459870-0018b994-15fa-4ee8-8c92-1eb84d36ba15.png">

**Comment by santoshbagadi** [comment]
It is odd that the Ad Review plugin is not added, but the error message seems to suggest that it has been added twice. I've tried to reproduce the issue on Unity 2022.2.1f1 and was not able to. 

Could you please try a clean build and then build on top to see if you are still seeing the issue.

Also, for my builds, Unity just seems to be re-creating all the `build.gradle` files again on each build. Do you know if you are using any new build settings that would cause Unity to not re-generate the gradle files?

**Comment by joshua-matchala** [comment]
I'm using 
<img width="440" alt="image" src="https://user-images.githubusercontent.com/75960319/214978930-344f5f9d-bff0-436e-be7a-92af60baf068.png">

Also, if I delete the 'bee' folder, then it creates the apk just fine, but it takes a long time every time. Basically building if the bee folder already exists is causing the problem.

I don't do any manual handling of build.gradle file, so it should be regenerating each time.

@santoshbagadi

**Comment by riverreal** [comment]
@santoshbagadi 
Sorry for bringing this up again but the issue still persists.
I'm currently using `Unity 2022.2.18f1` (I have been consistently reproducing it in other `2022.2.xx` versions), and the latest applovin plugin (`5.9.0`).
Subsequent builds create this redundant line in the `build.gradle`
```gradle
id 'com.applovin.quality' version '+' apply false // NOTE: Requires version 4.8.3+ for Gradle version 7.2+
id 'com.applovin.quality' version '+' apply false // NOTE: Requires version 4.8.3+ for Gradle version 7.2+
```
which makes the build fail.

So I have to manually remove both of them before building so it generates just one line and then succeeds with the build.

I think there is some setting somewhere in Unity that makes the `build.gradle` file not re-generate.

**Comment by santoshbagadi** [comment]
Hi @riverreal , do you mind checking if you are able to reproduce the issue with our demo app project: https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/tree/master/DemoApp

We've tried to reproduce the issue, but we are not able to on 2022.2.1. If you are able to reproduce the issue on a sample project, do you mind sharing the project with us, so that we can further investigate.

**Comment by santoshbagadi** [comment]
We've added a fix for this issue in our latest plugin [version 5.11.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_5_11_0).

**Comment by riverreal** [comment]
Thank you. I will try it out when I have time.
My apologies, I didn't have time to test the demo project.

**Comment by 0x00x0** [comment]
I have same issue. Any solutions? 
**MAX Plugin Version**
6.1.1

**Unity Version**
2022.3.11f1

**Device/Platform Info**
Unity Editor, Android Target

**Comment by santoshbagadi** [comment]
@0x00x0 do you mind providing the error logs that you are seeing when trying to build.

**Comment by 0x00x0** [comment]
@santoshbagadi 
part of build log:
```
Gradle file properties : Gradle Version : 7.1.2 
Compile Sdk Version : 33 
Target Sdk Version : 29 
BuildToolsVersion : 34.0.0

   Call "AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinPostProcessGradleProject.OnPostGenerateGradleAndroidProject" from assembly 'MaxSdk.Scripts.IntegrationManager.Editor'
Error [AppLovin MAX] Failed to add AppLovin Quality Service plugin to root gradle file.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
MaxSdkLogger:UserError (string) (at Assets/MaxSdk/Scripts/MaxSdkLogger.cs:55)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinProcessGradleBuildFile:AddPluginToRootGradleBuildFile (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinProcessGradleBuildFile.cs:146)
AppLovinMax.Scripts.IntegrationManager.Editor.AppLovinPostProcessGradleProject:OnPostGenerateGradleAndroidProject (string) (at Assets/MaxSdk/Scripts/IntegrationManager/Editor/AppLovinPostProcessAndroidGradle.cs:31)
```
Usage of gradle files
![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/23198572/5eddaa88-fd68-4f54-9624-615cd1d1f0b4)

Attached gradle files and properties
[baseProjectTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/13817842/baseProjectTemplate.txt)
[gradleTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/13817843/gradleTemplate.txt)
[launcherTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/13817844/launcherTemplate.txt)
[mainTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/13817845/mainTemplate.txt)
[settingsTemplate.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/13817846/settingsTemplate.txt)

**Comment by adizhavo** [comment]
This issue still persists in some cases, the problem is that there are duplicate lines in the generated gradle.build under .Project\...\Library\Bee\Android\Prj\IL2CPP\Gradle

Removing the duplicate line or deleting the file fixes the issue but it's until the next build gets made, this needs to be fixed from applovin

**Comment by MuhammedYlmz52** [comment]
I have the same problem with 2021.3.41f1 and none of the solutions here work for me.

**Comment by JonathanLiuApp** [comment]
@MuhammedYlmz52 This is actually caused by Google's EDM4U. In 2022.2+, they will automatically move your maven repos from your build.gradle file to the settings.gradle file, since this is needed for upgraded AGP versions. However, Unity upgraded the AGP version for 2021.3.41f1 and Google hasn't updated EDM4U to handle that. This will cause your maven repos to not work correctly and be unable to fetch your dependencies in your project. 

You can fix this by copying the maven repos into `repositories` section in your settings.gradle file. Also make sure you are using `RepositoriesMode.PREFER_SETTINGS` for this fix. The section it will be in should look something like this afterwards:

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "https://unity3ddist.jfrog.io/artifactory/unity-mediation-mvn-prod-local/"
        }
        maven {
            url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea"
        }
        mavenLocal()
        mavenCentral()
        google()
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
