### ISSUE TITLE
iOS13: NOT showing any ads.

### ISSUE THREAD

**Issue by Deroido** [AppLovin/AppLovin-MAX-Unity-Plugin#42]
Greetings.
I've already implemented AppLovin MAX on Android, everything works fine.
It's time for iOS, and as for now not a single ad was shown.

Here are details:
Unity 2019.3.14f1, Xcode 11.5
iPhone SE (iOS 13.4.1)
using latest MAX with latest adapters (Applovin, Adcolony, Facebook, TapJoy, Inmobi, Admob, UnityADS)

it looks like ad successful loaded but never shown.

> 2020-07-17 13:26:37.128894+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.135839+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.141811+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.150617+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.153604+0700 namespace[17424:12103825] I/UnityAds: +[USRVApiSdk WebViewExposed_logInfo:callback:] (line:67) :: mediation detection is:{"UnityEngine":true}
> 2020-07-17 13:26:37.156885+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.167583+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.174403+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.197019+0700 namespace[17424:12103825] I/UnityAds: +[USRVApiSdk WebViewExposed_logInfo:callback:] (line:67) :: Requesting configuration from https://publisher-config.unityads.unity3d.com/games/3487563/configuration?bundleId=com.namespace.game.free.namespace&encrypted=true&rooted=false&platform=ios&sdkVersion=3460&osVersion=13.4.1&deviceModel=iPhone8%2C4&language=en_RU&connectionType=wifi&screenHeight=568&screenWidth=320&test=false&analyticsSessionId=4686417068889972243&advertisingTrackingId=308254B9-CAA6-4327-8450-CBC9B41D1760&limitAdTracking=false&frameworkName=Unity&frameworkVersion=2019.3.14f1&adapterName=Packman&adapterVersion=3.4.2
> 2020-07-17 13:26:37.197886+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.198109+0700 namespace[17424:12103825] IOSNative::Native->Unity callback data: {"m_error":{"m_message":"","m_code":0}}
> 2020-07-17 13:26:37.427632+0700 namespace[17424:12103825] [ProcessSuspension] 0x1179d68b0 - ProcessAssertion::processAssertionWasInvalidated()
> 2020-07-17 13:26:37.427945+0700 namespace[17424:12103825] [ProcessSuspension] 0x1179d6910 - ProcessAssertion::processAssertionWasInvalidated()
> 2020-07-17 13:26:37.452204+0700 namespace[17424:12103825] [ProcessSuspension] 0x1179d6970 - ProcessAssertion::processAssertionWasInvalidated()
> 2020-07-17 13:26:37.452315+0700 namespace[17424:12103825] [ProcessSuspension] 0x1179d69d0 - ProcessAssertion::processAssertionWasInvalidated()
> 2020-07-17 13:26:37.511751+0700 namespace[17424:12103825] [ProcessSuspension] 0x1179d65e0 - ProcessAssertion::processAssertionWasInvalidated()
> 2020-07-17 13:26:37.578798+0700 namespace[17424:12103825] I/UnityAds: +[USRVApiSdk WebViewExposed_logInfo:callback:] (line:67) :: Received configuration for token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWMiOjI1MywiYXpwIjoiZDY2NzFmOGItYzJiZC00ODJhLWJiMDktZWE2MWQxOTgyMjA2IiwiY3BpIjoxNDcsImNyZWF0ZWQiOjE1NTI1OTMyNjEwMDAsImV4cCI6MTU5NjE3Njc5NywiaWFwIjozMywiaWF0IjoxNTk0OTY3MTk3LCJpc3MiOiJhZHMtZ2FtZS1jb25maWd1cmF0aW9uLnVuaXR5YWRzLnVuaXR5M2QuY29tIiwibHR2Ijo5NCwicHJvIjozMSwic3ViIjoiTkV5cmdRT3FQK04wWHFNUjYwN2ludVZRM2REb29SbGZDQnZtay9FZHVYaC83MlFYTlE0akdQd0wvN0FNUmVOeVNMeWFJUT09IiwieHByIjoyNDF9.0Y5mE03OwuK-J17BY92n9tUYihTCqW1HywYO78FGMBU (A/B group 19)
> 2020-07-17 13:26:37.583347+0700 namespace[17424:12103825] [ProcessSuspension] 0x1179d4d50 - ProcessAssertion::processAssertionWasInvalidated()
> 2020-07-17 13:26:37.611469+0700 namespace[17424:12103825] LTE
> 2020-07-17 13:26:37.625618+0700 namespace[17424:12103825] LTE
> 2020-07-17 13:26:37.627568+0700 namespace[17424:12103825] LTE
> **2020-07-17 13:26:37.638242+0700 namespace[17424:12103825] I/UnityAds: +[USRVApiSdk WebViewExposed_logInfo:callback:] (line:67) :: Requesting ad plan from https://auction.unityads.unity3d.com/v6/games/3487563/requests?advertisingTrackingId=308254B9-CAA6-4327-8450-CBC9B41D1760&limitAdTracking=false&deviceModel=iPhone8%2C4&platform=ios&sdkVersion=3460&stores=apple&osVersion=13.4.1&screenScale=2&screenWidth=320&screenHeight=568&connectionType=wifi&networkType=13
> 2020-07-17 13:26:37.875094+0700 namespace[17424:12103825] -canOpenURL: failed for URL: "about:blank" - error: "This app is not allowed to query for scheme about"
> 2020-07-17 13:26:38.283982+0700 namespace[17424:12103825] <Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"83d65ec28bb7f8c488abfe2d49194bd0" ];**
> 2020-07-17 13:26:39.417160+0700 namespace[17424:12103825] LTE
> [AppLovin MAX] Invoking event: System.Action`1[System.String]. Param: 5aab027d2ff7609c
> MaxSdkCallbacks:InvokeEvent(Action`1, T)
> MaxSdkCallbacks:ForwardEvent(String)
>  
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> AppLovin OnRewardedAdLoadedEvent 5aab027d2ff7609c
> System.Action`1:Invoke(T)
> MaxSdkCallbacks:ForwardEvent(String)
>  
> (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
> 
> **2020-07-17 13:27:06.071603+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> 2020-07-17 13:27:06.077121+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
> 2020-07-17 13:27:07.305891+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> 2020-07-17 13:27:07.307343+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
> 2020-07-17 13:27:07.325402+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> 2020-07-17 13:27:07.328028+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
> 2020-07-17 13:27:07.388844+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
> 2020-07-17 13:27:07.390005+0700 namespace[17424:12103825] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service**
> 2020-07-17 13:27:14.215962+0700 namespace[17424:12104281] [] tcp_input [C23.1:3] flags=[R.] seq=1636781501, ack=3462117648, win=461 state=CLOSED rcv_nxt=1636781477, snd_una=3462117647

> 2020-07-17 13:27:23.067086+0700 namespace[17424:12103825] [AppLovinSdk] DEBUG [MARewardedAd] Created new MARewardedAd (<MAFullscreenAdController: 0x283caa700>)
> 
```
 2020-07-17 13:27:42.878059+0700 namespace[17424:12104082] [] tcp_input [C15.1:3] flags=[R] seq=2802310388, ack=0, win=0 state=LAST_ACK rcv_nxt=2802310389, snd_una=2923390154
 2020-07-17 13:27:42.882060+0700 namespace[17424:12104082] [] tcp_input [C15.1:3] flags=[R] seq=2802310388, ack=0, win=0 state=LAST_ACK rcv_nxt=2802310389, snd_una=2923390154
 2020-07-17 13:27:42.886197+0700 namespace[17424:12104281] [] tcp_input [C15.1:3] flags=[R] seq=2802310389, ack=0, win=0 state=LAST_ACK rcv_nxt=2802310389, snd_una=2923390154
 2020-07-17 13:27:42.888094+0700 namespace[17424:12104281] [] tcp_input [C15.1:3] flags=[R] seq=2802310389, ack=0, win=0 state=CLOSED rcv_nxt=2802310389, snd_una=2923390154
 2020-07-17 13:27:47.802063+0700 namespace[17424:12104082] [] tcp_input [C33.1:3] flags=[R] seq=733807108, ack=0, win=0 state=LAST_ACK rcv_nxt=733807108, snd_una=414071709
 2020-07-17 13:27:47.808377+0700 namespace[17424:12104082] [] tcp_input [C33.1:3] flags=[R] seq=733807108, ack=0, win=0 state=CLOSED rcv_nxt=733807108, snd_una=414071709
 2020-07-17 13:27:47.816558+0700 namespace[17424:12104638] [] tcp_input [C33.1:3] flags=[R] seq=733807108, ack=0, win=0 state=CLOSED rcv_nxt=733807108, snd_una=414071709
 2020-07-17 13:28:53.543252+0700 namespace[17424:12104082] [] tcp_input [C40.1:3] flags=[R] seq=3549595803, ack=0, win=0 state=LAST_ACK rcv_nxt=3549595804, snd_una=2257225396
 2020-07-17 13:28:53.543977+0700 namespace[17424:12104082] [] tcp_input [C40.1:3] flags=[R] seq=3549595803, ack=0, win=0 state=LAST_ACK rcv_nxt=3549595804, snd_una=2257225396
 2020-07-17 13:28:53.546489+0700 namespace[17424:12104082] [] tcp_input [C40.1:3] flags=[R] seq=3549595804, ack=0, win=0 state=LAST_ACK rcv_nxt=3549595804, snd_una=2257225396
 2020-07-17 13:28:53.547465+0700 namespace[17424:12104082] [] tcp_input [C40.1:3] flags=[R] seq=3549595804, ack=0, win=0 state=CLOSED rcv_nxt=3549595804, snd_una=2257225396
 2020-07-17 13:32:43.621245+0700 namespace[17424:12105138] [] tcp_input [C42.1:3] flags=[R] seq=1611248326, ack=0, win=0 state=LAST_ACK rcv_nxt=1611248327, snd_una=645224610
 2020-07-17 13:32:43.630423+0700 namespace[17424:12104638] [] tcp_input [C42.1:3] flags=[R] seq=1611248326, ack=0, win=0 state=LAST_ACK rcv_nxt=1611248327, snd_una=645224610
 2020-07-17 13:32:43.635392+0700 namespace[17424:12104638] [] tcp_input [C42.1:3] flags=[R] seq=1611248327, ack=0, win=0 state=LAST_ACK rcv_nxt=1611248327, snd_una=645224610
 2020-07-17 13:32:43.637046+0700 namespace[17424:12104638] [] tcp_input [C42.1:3] flags=[R] seq=1611248327, ack=0, win=0 state=CLOSED rcv_nxt=1611248327, snd_una=645224610
```

this really doesn't look right  
![image](https://user-images.githubusercontent.com/201954/87779286-c40ab480-c856-11ea-8e09-6521fda3125b.png)

I'm not using this device in MAX Test Mode yet. Would Like to see any real ad 1st (not exact network).

So as far ad I can judge there's a problem with WebView and so UnityAds url looks like 'about:blank'.
There are some guides in the internet corresponding to this problem, but they all require native code adaptation which is impossible with unity plugin.

Could you please help? I can share more info with real (not 'namespace') entries.

**Comment by Deroido** [comment]
here are more details. unmodified log, also with initialization 

[AppLovin ios details.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/4937371/AppLovin.ios.details.txt)

**Comment by Deroido** [comment]
here's full verbose log

[ios max verbose log.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/4938503/ios.max.verbose.log.txt)

I repeat. I'm not using TEST mode yet.
For now I can't share the build, but maybe this will be the case if we struggle to solve this.

**Comment by santoshbagadi** [comment]
@Deroido , In the logs I could see any calls our show methods. Could you double check that our `ShowInterstitial` is being called. 

We would also strongly recommend testing with Test ads first, to ensure that the integration is working correctly and then move to live ads if you would like.

**Comment by Deroido** [comment]
I'm sorry. this was my mistake.
I was checking rewarded ad availability by placement, and not adUnit ad it should be. Also the log still wasn't verbose.
Now I can see ads.  So lets forget about this.

But there are few things noticed. I'm not gonna create new thread yet.

With this (a little outdated) configuration everything works fine:
![image](https://user-images.githubusercontent.com/201954/87856397-1b894d00-c949-11ea-9dd7-bf7fd07b9c8f.png)


if I clock all UPDATE buttons Unity builds fine, but Xcode won't build with 1 unexpected error
![image](https://user-images.githubusercontent.com/201954/87856433-5e4b2500-c949-11ea-881a-71d22c63cfc7.png)

please re-check that.

In some other configurations I could build but the app crashes right after MAX initialization:
![image](https://user-images.githubusercontent.com/201954/87856450-78850300-c949-11ea-970f-920f31627c74.png)
[MAX CRASH.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/4941944/MAX.CRASH.txt)


As for now I'm gonna rollback some mediation versions and check stability with each one.
We use Applovin, Adcolony, Facebook, TapJoy, Inmobi, Admob, UnityADS.
I can confirm that it's **not** Applovin and **not** Admob. Others are questionable.   Could you comment on that behavior?
If I found exact module causing this I will post it there.

**Comment by Deroido** [comment]
It's unity ads causing crash on real device. Please check update from 3.4.6.0 to 3.4.6.2
Adcolony, Inmobi or TapJoy won't even let me build with unexpected failure. I don't have more time to check exact mediator causing this.

right now using this configuration which seems to work fine:
![image](https://user-images.githubusercontent.com/201954/87857004-59887000-c94d-11ea-923b-59fcf7ed1679.png)

**Comment by thomasmso** [comment]
Hey @Deroido - you're right on that - we pushed out new adapters that fixes it, could you try again?

**Comment by Deroido** [comment]
> 
> 
> Hey @Deroido - you're right on that - we pushed out new adapters that fixes it, could you try again?

with all the latest adapters this unknown error still persists.

![image](https://user-images.githubusercontent.com/201954/88391143-cb483a00-cde3-11ea-9b2f-9bed7d1b53ad.png)

I will try to remove adapters one by one

**Comment by Deroido** [comment]
this error was related to TapJoy Adapter.

previous version causes crashes in runtime *(on initialization)
the latest version won't let me build in xcode.
![image](https://user-images.githubusercontent.com/201954/88391909-4827e380-cde5-11ea-828e-35512c7c6ff9.png)

**Comment by richashukla23** [comment]
@Deroido Good to know that you were able to narrow down on TapJoy Adapter. 

Regarding the build issue with the latest version - can you please try Product > Clean Build Folder and try build again? 

I would reiterate that we strongly recommend that you use test ads during this phase.

**Comment by thomasmso** [comment]
@Deroido - Do you have any updates on your issue?

**Comment by Deroido** [comment]
> 
> 
> @Deroido - Do you have any updates on your issue?

Im sorry for long response.  We've decided to exclude TapJoy from our iOS build. So no updates on that
