### ISSUE TITLE
Unity 6 Real Ads don't show with android

### ISSUE THREAD

**Issue by hunght85** [AppLovin/AppLovin-MAX-Unity-Plugin#421]
### MAX Plugin Version

6.6.3

### Unity Version

6000.17f.Preview

### Device/Platform Info

Android

### Current Behavior

ads no fill for android (Playstore) after use latest plugin with Unity 6. iOS work well. Have anyonce has same my problem?
Remark: Other app with other version unity and lower version AppLovin plugin still report has ads show.

### How to Reproduce

Remark: Other app with other version unity and lower version AppLovin plugin still report has ads show.

**Comment by JonathanLiuApp** [comment]
@hunght85 I wasn't able to reproduce your issue. Could you send the full logs for the session where you get no ads?

**Comment by HassannKhan** [comment]
I am facing the same issue, I have been sending emails about it but the funny thing is, they will only waste time demanding verbose logs like things. As an indie game developer, I don't have time to do AppLovin's JOB. Due to their negligence, I am losing revenue. AppLOVIN should consider keeping a check on his team's laziness. If you want verbose logs so badly, why don't you get it on your own?


@hunght85 If you can't reproduce the issue, that's no excuse sweetheart. Just set a time with us and see it for yourself in our devices using anydesk or something.

**Comment by hunght85** [comment]
> I am facing the same issue, I have been sending emails about it but the funny thing is, they will only waste time demanding verbose logs like things. As an indie game developer, I don't have time to do AppLovin's JOB. Due to their negligence, I am losing revenue. AppLOVIN should consider keeping a check on his team's laziness. If you want verbose logs so badly, why don't you get it on your own?
> 
> @hunght85 If you can't reproduce the issue, that's no excuse sweetheart. Just set a time with us and see it for yourself in our devices using anydesk or something.

I use Admob directly for android right now. I hope AppLovin define problem soon

**Comment by thomasmso** [comment]
@HassannKhan - We'd hate for you to lose more revenue, if you could enable and send over [verbose logs](https://developers.applovin.com/en/max/unity/overview/advanced-settings/#enable-verbose-logging) of you attempting to load an ad we might be able to identify the issue.

**Comment by thomasmso** [comment]
Dear @HassannKhan - I have the utmost confidence that you can set `MaxSdk.SetVerboseLogging(true);` in your app and send over the log output. Hint: our logs have the tag `AppLovinSdk`.

**Comment by HassannKhan** [comment]
@thomasmso Sorry to let you down. I failed to set in my app. Thanks for your confidence though. Feel free to join my anydesk any time and get your verbose as much/as many as you want DEAR

**Comment by hunght85** [comment]
2024-10-21 05:16:21.228  7481-7516  Unity                   E  AndroidJavaException: java.lang.NoSuchMethodError: No static method builder(Ljava/lang/String;Landroid/content/Context;)Lcom/applovin/sdk/AppLovinSdkInitializationConfiguration$Builder; in classLcom/applovin/sdk/AppLovinSdkInitializationConfiguration; or its super classes (declaration of 'com.applovin.sdk.AppLovinSdkInitializationConfiguration' appears in/data/app/~~mbkjwOqC4Zr2_ULJekB4QA==/AppPackage-gVdLSWyVqSEkfdq_HCWJ9A==/base.apk)
java.lang.NoSuchMethodError: No static method builder(Ljava/lang/String;Landroid/content/Context;)Lcom/applovin/sdk/AppLovinSdkInitializationConfiguration$Builder; in class Lcom/applovin/sdk/AppLovinSdkInitializationConfiguration; or its super classes (declaration of 'com.applovin.sdk.AppLovinSdkInitializationConfiguration' appears in /data/app/~~mbkjwOqC4Zr2_ULJekB4QA==/com.navmeshagent.FakePoliceCall-gVdLSWyVqSEkfdq_HCWJ9A==/base.apk)
                                                                                                    	at com.applovin.mediation.unity.MaxUnityPlugin.createInitConfigurationBuilder(MaxUnityPlugin.java:1083)

**Comment by hunght85** [comment]
> @thomasmso Sorry to let you down. I failed to set in my app. Thanks for your confidence though. Feel free to join my anydesk any time and get your verbose as much/as many as you want DEAR

under is capture error
2024-10-21 05:16:21.228  7481-7516  Unity                   E  AndroidJavaException: java.lang.NoSuchMethodError: No static method builder(Ljava/lang/String;Landroid/content/Context;)Lcom/applovin/sdk/AppLovinSdkInitializationConfiguration$Builder; in classLcom/applovin/sdk/AppLovinSdkInitializationConfiguration; or its super classes (declaration of 'com.applovin.sdk.AppLovinSdkInitializationConfiguration' appears in/data/app/~~mbkjwOqC4Zr2_ULJekB4QA==/AppPackage-gVdLSWyVqSEkfdq_HCWJ9A==/base.apk)
java.lang.NoSuchMethodError: No static method builder(Ljava/lang/String;Landroid/content/Context;)Lcom/applovin/sdk/AppLovinSdkInitializationConfiguration$Builder; in class Lcom/applovin/sdk/AppLovinSdkInitializationConfiguration; or its super classes (declaration of 'com.applovin.sdk.AppLovinSdkInitializationConfiguration' appears in /data/app/~~mbkjwOqC4Zr2_ULJekB4QA==/com.navmeshagent.FakePoliceCall-gVdLSWyVqSEkfdq_HCWJ9A==/base.apk)
                                                                                                    	at com.applovin.mediation.unity.MaxUnityPlugin.createInitConfigurationBuilder(MaxUnityPlugin.java:1083)

**Comment by santoshbagadi** [comment]
@hunght85 Thank you for sharing the logs. We've found the root cause of the issue, and the issue happens specifically when setting `minSdkVersion` < 24 due to Gradle and Java version mismatch. We'll have a fix for this in our next release and notify here when it is out.

**Comment by cemtuver-applovin** [comment]
Hello @hunght85, @HassannKhan! We have released a new version of our SDK, 13.0.1 (Unity Plugin 8.0.1), which addresses this issue. Could you please update your AppLovin version to the latest?

**Comment by HassannKhan** [comment]
@cemtuver-applovin Sweet friend, I wonder why you rushed to mark it as complete as the issue is still there.
I just tested your new plugin AppLovin-MAX-Unity-Plugin-8.0.0-Android-13.0.0-iOS-13.0.0
This still does not show any advertisement on android devices unless you change your API level to 24 or higher.

Although this solution works fine for the ads but Changing API 24 removes around 2k supported devices which means a big chunk of user loss so the solution is not the ideal one.

**Comment by HassannKhan** [comment]
<img width="960" alt="PictureForCemtuver" src="https://github.com/user-attachments/assets/c41d8585-3b3b-4b79-a115-7873323db16d">



Sadly :(

**Comment by cemtuver-applovin** [comment]
Hi @HassannKhan thank you very much letting us know! I am happy to hear that the issue has been resolved.

**Comment by HassannKhan** [comment]
@cemtuver-applovin Thank you so much for being so cooperative. I have one more issue though. Do you want me to open new issue for that ?

**Comment by cemtuver-applovin** [comment]
Thank you for your message, @HassannKhan! We’re all happy to help. For the other issue, could you please create a ticket for our support team in [our Support Center](https://developers.applovin.com/en)? Just scroll to the bottom of the page and click the "Log in to Zendesk" button. From there, you can submit a ticket and communicate directly with our support team.

**Comment by HassannKhan** [comment]
@cemtuver-applovin Same issue is back again.... Apparently, I had two versions of unity installed in my computer. When I removed the other version. It stopped working again.  Sweet !!!

**Comment by HassannKhan** [comment]
Unity version 6000.0.15f1 and 6000.0.28f1
Applovin Plugin Version 8.0.1
Error Message - same as attached screenshot above
Groovy related

**Comment by cemtuver-applovin** [comment]
Thank you for sharing the details, @HassannKhan.
We’re investigating this issue and will keep you updated.

**Comment by cemtuver-applovin** [comment]
Hi @HassannKhan. I have been trying to replicate the issue, but it doesn’t seem to occur in my test environment. Would you be able to create a sample Unity project where the issue reproduces and share it with me?

**Comment by HassannKhan** [comment]
I don't think sample project will reproduce the same issue in your side, if you are not having the issue in the first place.

**Comment by cemtuver-applovin** [comment]
Hi @HassannKhan. Without a reproducible case, it may not be possible to investigate further. 

Have you tried force-resolving dependencies through the External Dependency Manager? Alternatively, Would you be able to revert to the Unity Editor version that was previously working for your case?
