### ISSUE TITLE
ios build issue

### ISSUE THREAD

**Issue by Kidkiwi** [AppLovin/AppLovin-MAX-Unity-Plugin#473]
### MAX Plugin Version

latest

### Unity Version

unity 6

### Device/Platform Info

ios

### Current Behavior

The latest sdk version has iOS build issues.

ld: warning: ignoring duplicate libraries: '-lc++', '-lsqlite3.0'
ld: warning: Could not find or use auto-linked library 'swift_Builtin_float': library 'swift_Builtin_float' not found
ld: warning: Could not find or use auto-linked library 'swift_errno': library 'swift_errno' not found
ld: warning: Could not find or use auto-linked library 'swift_math': library 'swift_math' not found
ld: warning: Could not find or use auto-linked library 'swift_signal': library 'swift_signal' not found
ld: warning: Could not find or use auto-linked library 'swift_stdio': library 'swift_stdio' not found
ld: warning: Could not find or use auto-linked library 'swift_time': library 'swift_time' not found
ld: warning: Could not find or use auto-linked library 'swiftsys_time': library 'swiftsys_time' not found
ld: warning: Could not find or use auto-linked library 'swiftunistd': library 'swiftunistd' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'MACAVPlayer': framework 'MACAVPlayer' not found
ld: warning: Could not find or use auto-linked framework 'MACAdsQuality': framework 'MACAdsQuality' not found
ld: warning: Could not find or use auto-linked framework 'MACAnalytics': framework 'MACAnalytics' not found
ld: warning: Could not find or use auto-linked framework 'MACBase': framework 'MACBase' not found
ld: warning: Could not find or use auto-linked framework 'MACBaseUI': framework 'MACBaseUI' not found
ld: warning: Could not find or use auto-linked framework 'MACCAChallengeHandler': framework 'MACCAChallengeHandler' not found
ld: warning: Could not find or use auto-linked framework 'MACClientBidding': framework 'MACClientBidding' not found
ld: warning: Could not find or use auto-linked framework 'MACConsent': framework 'MACConsent' not found
ld: warning: Could not find or use auto-linked framework 'MACConstants': framework 'MACConstants' not found
ld: warning: Could not find or use auto-linked framework 'MACCrashlytics': framework 'MACCrashlytics' not found
ld: warning: Could not find or use auto-linked framework 'MACDebugPanel': framework 'MACDebugPanel' not found
ld: warning: Could not find or use auto-linked framework 'MACDependenciesUmbrella': framework 'MACDependenciesUmbrella' not found
ld: warning: Could not find or use auto-linked framework 'MACDivKit': framework 'MACDivKit' not found
ld: warning: Could not find or use auto-linked framework 'MACEncryption': framework 'MACEncryption' not found
ld: warning: Could not find or use auto-linked framework 'MACEventTracking': framework 'MACEventTracking' not found
ld: warning: Could not find or use auto-linked framework 'MACFalseClickKit': framework 'MACFalseClickKit' not found
ld: warning: Could not find or use auto-linked framework 'MACFeatureFlags': framework 'MACFeatureFlags' not found
ld: warning: Could not find or use auto-linked framework 'MACHeaderBidding': framework 'MACHeaderBidding' not found
ld: warning: Could not find or use auto-linked framework 'MACLogging': framework 'MACLogging' not found
ld: warning: Could not find or use auto-linked framework 'MACMediation': framework 'MACMediation' not found
ld: warning: Could not find or use auto-linked framework 'MACMraid': framework 'MACMraid' not found
ld: warning: Could not find or use auto-linked framework 'MACNative': framework 'MACNative' not found
ld: warning: Could not find or use auto-linked framework 'MACNetworking': framework 'MACNetworking' not found
ld: warning: Could not find or use auto-linked framework 'MACPlatformDescription': framework 'MACPlatformDescription' not found
ld: warning: Could not find or use auto-linked framework 'MACSDKConfiguration': framework 'MACSDKConfiguration' not found
ld: warning: Could not find or use auto-linked framework 'MACStoreKit': framework 'MACStoreKit' not found
ld: warning: Could not find or use auto-linked framework 'MACTimeTracking': framework 'MACTimeTracking' not found
ld: warning: Could not find or use auto-linked framework 'MACVASTKit': framework 'MACVASTKit' not found
ld: warning: Could not find or use auto-linked framework 'MobileAdsCore': framework 'MobileAdsCore' not found
ld: warning: Could not find or use auto-linked framework 'SwiftUICore': framework 'SwiftUICore' not found
ld: warning: Could not find or use auto-linked framework 'UnitySwiftProtobuf': framework 'UnitySwiftProtobuf' not found
ld: warning: Could not find or use auto-linked framework 'YandexMobileAds_Private': framework 'YandexMobileAds_Private' not found
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swift_Builtin_float", referenced from:
      __swift_FORCE_LOAD_$_swift_Builtin_float_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_errno", referenced from:
      __swift_FORCE_LOAD_$_swift_errno_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_math", referenced from:
      __swift_FORCE_LOAD_$_swift_math_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_signal", referenced from:
      __swift_FORCE_LOAD_$_swift_signal_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_stdio", referenced from:
      __swift_FORCE_LOAD_$_swift_stdio_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_time", referenced from:
      __swift_FORCE_LOAD_$_swift_time_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swiftsys_time", referenced from:
      __swift_FORCE_LOAD_$_swiftsys_time_$_IronSource in IronSource[628](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swiftunistd", referenced from:
      __swift_FORCE_LOAD_$_swiftunistd_$_IronSource in IronSource[628](AbTestMapFile.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you guys test these before releasing?

### How to Reproduce

Just build to iOS

### Reproducible in the demo app?

Yes

**Comment by alvarshahanji** [comment]
Can you try using Xcode 16?

**Comment by jkulisic** [comment]
We hit the same issue when building using Unity version 2022.3.53 & Xcode 15.4. We cannot use a more recent Xcode version as Unity Cloud Build does not support any later versions

**Comment by alvarshahanji** [comment]
Looks like IronSource 8.6.0.0 requires Xcode 16( [changelog](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/blob/master/IronSource/CHANGELOG.md#85100) ). Could you try using IronSource adapter 8.5.0.0.0? That should resolve these errors

**Comment by alvarshahanji** [comment]
Latest [Facebook adapter(SDK)](https://github.com/AppLovin/AppLovin-MAX-SDK-iOS/blob/master/Facebook/CHANGELOG.md#61600) also has Xcode 16 requirements. 

Also, Unity Cloud Build has started supporting Xcode 16([documentation](https://docs.unity.com/ugs/manual/devops/manual/build-automation/reference/available-xcode-versions)). So you should be able to use all the latest adapters with Xcode 16 now.

**Comment by Kidkiwi** [comment]
@alvarshahanji I use the latest version of xcode, always do. 16.2. Issue still occurs.

**Comment by Kidkiwi** [comment]
`ld: warning: ignoring duplicate libraries: '-lc++', '-lsqlite3.0'
ld: warning: Could not find or use auto-linked library 'swift_Builtin_float': library 'swift_Builtin_float' not found
ld: warning: Could not find or use auto-linked library 'swift_errno': library 'swift_errno' not found
ld: warning: Could not find or use auto-linked library 'swift_math': library 'swift_math' not found
ld: warning: Could not find or use auto-linked library 'swift_signal': library 'swift_signal' not found
ld: warning: Could not find or use auto-linked library 'swift_stdio': library 'swift_stdio' not found
ld: warning: Could not find or use auto-linked library 'swift_time': library 'swift_time' not found
ld: warning: Could not find or use auto-linked library 'swiftsys_time': library 'swiftsys_time' not found
ld: warning: Could not find or use auto-linked library 'swiftunistd': library 'swiftunistd' not found
ld: warning: Could not find or use auto-linked framework 'CoreAudioTypes': framework 'CoreAudioTypes' not found
ld: warning: Could not find or use auto-linked framework 'SwiftUICore': framework 'SwiftUICore' not found
ld: warning: Could not find or use auto-linked framework 'UnitySwiftProtobuf': framework 'UnitySwiftProtobuf' not found
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swift_Builtin_float", referenced from:
      __swift_FORCE_LOAD_$_swift_Builtin_float_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swift_Builtin_float_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swift_Builtin_float_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swift_Builtin_float_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swift_Builtin_float_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_errno", referenced from:
      __swift_FORCE_LOAD_$_swift_errno_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swift_errno_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swift_errno_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swift_errno_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swift_errno_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_math", referenced from:
      __swift_FORCE_LOAD_$_swift_math_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swift_math_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swift_math_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swift_math_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swift_math_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_signal", referenced from:
      __swift_FORCE_LOAD_$_swift_signal_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swift_signal_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swift_signal_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swift_signal_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swift_signal_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_stdio", referenced from:
      __swift_FORCE_LOAD_$_swift_stdio_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swift_stdio_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swift_stdio_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swift_stdio_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swift_stdio_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swift_time", referenced from:
      __swift_FORCE_LOAD_$_swift_time_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swift_time_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swift_time_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swift_time_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swift_time_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swiftsys_time", referenced from:
      __swift_FORCE_LOAD_$_swiftsys_time_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swiftsys_time_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swiftsys_time_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swiftsys_time_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swiftsys_time_$_IronSource in IronSource[621](AbTestMapFile.o)
  "__swift_FORCE_LOAD_$_swiftunistd", referenced from:
      __swift_FORCE_LOAD_$_swiftunistd_$_FBAudienceNetworkSwift in FBAudienceNetwork[2](FBAudienceNetworkSwift.o)
      __swift_FORCE_LOAD_$_swiftunistd_$_FBAdFilterEngine in FBAudienceNetwork[3](FBAdFilterEngine.o)
      __swift_FORCE_LOAD_$_swiftunistd_$_FBAdMAISKOverlayManager in FBAudienceNetwork[4](FBAdMAISKOverlayManager.o)
      __swift_FORCE_LOAD_$_swiftunistd_$_FBAudienceNetwork in FBAudienceNetwork[406](FBAudienceNetwork.o)
      __swift_FORCE_LOAD_$_swiftunistd_$_IronSource in IronSource[621](AbTestMapFile.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`


I'm using the latest xcode, latest unity 6 lts and the latest applovin sdk/adapters.
