### ISSUE TITLE
Google Play warning about resizability and orientation restrictions on AppLovin apps

### ISSUE THREAD

**Issue by toxikman** [AppLovin/AppLovin-MAX-Unity-Plugin#516]
### MAX Plugin Version

8.1.0 (android SDK 13.1.0)

### Unity Version

6000.1.49f1

### Device/Platform Info

Android, Google Play

### Current Behavior

After submitting and publishing our Unity Android app that uses library "com.applovin:applovin-sdk:13.1.0", Google Play Console is giving us a warning about AppLovin's manifest activity settings:

> **Remove resizability and orientation restrictions in your game to support large screen devices**
> Your game doesn't support all display configurations, and uses resizability and orientation restrictions that may lead to layout issues for your users.
> 
> We detected the following resizability and orientation restrictions in your game:
> ```
> <activity android:name="com.applovin.adview.AppLovinFullscreenActivity" android:screenOrientation="BEHIND" />
> com.applovin.impl.mediation.debugger.ui.testmode.a.onCreate
> ```
> To improve the user experience of your game, remove these restrictions and check that your game layouts work on various screen sizes and orientations.

### Expected Behavior

SDKs should not create warnings that appear in popular marketplaces for a significant number of apps that are published on these marketplaces.

### How to Reproduce

Create a Unity 6 app that uses AppLovin SDK and publish it on Google Play.

### Reproducible in the demo app?

Not Tested

**Comment by applovinAsh** [comment]
Hi @toxikma. Is your app is targeting Android 16? The warning appears to be related to behavior changes introduced in Android 16. We're aware of the issue and are currently working on a fix. We'll keep you updated once it's released.

**Comment by kreativityapps** [comment]
Hi, is this going to be fixed on Flutter and Android as well?

Using the latest applovin_max: 4.5.2 Flutter version, which uses com.applovin:applovin-sdk:13.4.0

I get this warning in Google Play:

```
Remove resizability and orientation restrictions in your app to support large screen devices

From Android 16, Android will ignore resizability and orientation restrictions for large screen devices, such as foldables and tablets. This may lead to layout and usability issues for your users.

We detected the following resizability and orientation restrictions in your app:

    <activity android:name="com.applovin.adview.AppLovinFullscreenImmersiveActivity" android:screenOrientation="BEHIND" />
    <activity android:name="com.applovin.adview.AppLovinFullscreenActivity" android:screenOrientation="BEHIND" />
    com.applovin.impl.mediation.debugger.ui.testmode.a.onCreate

To improve the user experience for your app, remove these restrictions and check that your app layouts work on various screen sizes and orientations by testing on Android 16 and below.
```

This was reported already in May and it's already September. Any progress on it?

**Comment by santoshbagadi** [comment]
Hi @kreativityapps , this should not be an issue, since the flag `behind` is not of the params that is being deprecated by Google: https://developer.android.com/guide/topics/manifest/activity-element#screen

You can safely ignore this warning, and our ads would render fine on all devices.

**Comment by kreativityapps** [comment]
How about `com.applovin.impl.mediation.debugger.ui.testmode.a.onCreate`? Why is this in the release?

**Comment by cemtuver-applovin** [comment]
Hey all! Although this shouldn't be an issue, we have released a new version of our Android SDK, 13.5.0, which addresses the warnings on the Google Play Console. Please update your AppLovin SDK.

@kreativityapps `com.applovin.impl.mediation.debugger.ui.testmode.a` is part of our [Mediation Debugger](https://support.axon.ai/en/max/android/testing-networks/mediation-debugger/) tool.

**Comment by PickleJesus123** [comment]
I'm using the most recent version, 8.5.0. Not fixed! My Google Play console says:

We detected the following resizability and orientation restrictions in your game:
activity android:name="com.applovin.adview.AppLovinFullscreenActivity" android:screenOrientation="BEHIND"
activity android:name="com.bytedance.sdk.openadsdk.activity.TTWebsiteActivity" android:screenOrientation="PORTRAIT"
com.bytedance.sdk.openadsdk.activity.TTAppOpenAdActivity.fs

I'm also seeing a new error. One or more of the APIs you use or parameters that you set for edge-to-edge and window display have been deprecated in Android 15. Your app uses the following deprecated APIs or parameters: LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
These start in the following places:
com.applovin.adview.AppLovinFullscreenActivity.a
com.google.android.gms.ads.internal.overlay.zzm.zzJ
