### ISSUE TITLE
Ads are not serving immediately when the app is first installed and opened

### ISSUE THREAD

**Issue by sunilFlyingCaps** [AppLovin/AppLovin-MAX-Unity-Plugin#518]
### MAX Plugin Version

AppLovin [8.1.0] 

### Unity Version

2022.3.32

### Device/Platform Info

Android

### Current Behavior

It takes 1 to 2 minutes, even with high speed internet ,for ads to start serving in AppLovin MAX mediation, even though the ads are preloaded

### Expected Behavior

Ads should immediately show after initialization. 

### How to Reproduce

Initialize app lovin SDK
Load and show ad
Ad not showing.

### Reproducible in the demo app?

Yes

### Additional Info

Issue only shows up first time on a freshly installed application. Also It works fine after closing and reopening the application.

**Comment by volodymyrpukha** [comment]
I think I'm experiencing the same issue: the interstitial ad is not showing upon the first trigger, as if it hasn't been initialized yet, regardless of how much time has passed since the game launch. It's always on the second trigger.

Rewarded Ads work fine.

**Comment by applovinAsh** [comment]
Hi @sunilFlyingCaps & @volodymyrpukha. To help us understand what is going on in greater detail, please send us verbose logs from a session where this issue occurs. Please include the AppLovin SDK initialization in the log, as a lot of important information is logged at that time. 

For instructions on how to turn on AppLovin SDK verbose logging, see our documentation: https://developer.applovin.com/en/faq/how-to-enable-verbose-logging-in-the-applovin-sdk.

**Comment by volodymyrpukha** [comment]
Hi, my issue is resolved. It was a security measure in the SDK containing AppLovin MAX, to prevent an early ad display.

**Comment by sunilFlyingCaps** [comment]
@applovinAsh  Hi, I have attached the logs and also videos if thats helpful. Pls check. We also tried version [8.2.1], but the issue is still persisting. 
@volodymyrpukha can you tell me where that security measure is? Did you remove it? How did you resolve it? Thanks. 

[Aplovin ads issue.zip](https://github.com/user-attachments/files/20572799/Aplovin.ads.issue.zip)

**Comment by applovinAsh** [comment]
Hi @sunilFlyingCaps. Thank you for providing the logs. They show you are experiencing a "Failed to connect to server" error. This can happen when your device has connectivity issues caused by an ad blocker, VPN usage, a Firewall, or a Proxy. Can you connect to a different network and turn ad blockers off?

**Comment by applovinAsh** [comment]
Can you try using a different network or mobile internet connection and see that fixes the issue? located in GB does not have a CMP integrated.

**Comment by applovinAsh** [comment]
Can you try using a different network or mobile connection? Can you also try a different device? As stated previously, the device cannot communicate with our servers, which is usually caused by Ad Blocker. If you are testing in an office, you may need to work with your IT team to allow communication to our servers.

**Comment by applovinAsh** [comment]
Hi @sunilFlyingCaps, your logs show that you are making an ad request before the SDK is initialized. You should wait to make an ad request until the SDK is initialized for the best experience. If the issue persists, please provide new verbose logs from the start of a session.
